### ISSUE TITLE
Transaction with NACK is reported as OK

### ISSUE THREAD

**Issue by alpakpinar** [luigicalligaris/h7i2c-baremetal-driver#3]
Current implementation of the I2C driver returns `H7I2C_RET_CODE_OK` in the case of an ACK bit not being received back. Would it be possible to handle the case of NACK with a different return code? This would help downstream applications to handle this case more easily (e.g. you can see [here](https://gitlab.com/BU-EDF/openipmc-fw/-/blob/feature/h7i2c-driver/board_specific/cm_sensors.c#L102-124)). Thanks!

**Comment by luigicalligaris** [comment]
Fixed in commit 109d42063488ca9547f3365b9ab038dd64fafebd where H7I2C_RET_CODE_PERIPH_IN_ERR_STATE is returned if the driver enters an error state. It's then the user's responsibility to read out which error state the driver is in and act accordingly.
